services:
  grafana-lgtm:
    image: grafana/otel-lgtm:latest
    container_name: grafana-lgtm
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
#    environment:
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - C:\docker_volumes\elk\grafana-data:/var/lib/grafana
    restart: unless-stopped