spring:
  profiles:
    active:
      - EN
      - dog
      - dev
#guru:
#  username: YmlDbUser
#  password: YmlPassword
#  jdbcurl:  YmlUrlforDB

---
spring:
  profiles: prod

guru:
  username: YmlProdDbUser
  password: YmlProdPassword
  jdbcurl:  YmlProdUrlforDB
