package com.lavalliere.daniel.spring.spring6restmvc.mappers;

import com.lavalliere.daniel.spring.spring6restmvc.domain.Beer;
import com.lavalliere.daniel.spring.spring6restmvc.model.BeerDTO;
import org.mapstruct.Mapper;


@Mapper
// Code autogenerated based on MapStruct
public interface BeerMapper {

    Beer beerDtoToBeer(BeerDTO dto);
    BeerDTO beerToBeerDto(Beer beer);
}
